# === anti-echo-chamber project config (v2: ideology-aware stance) ===
version: 2

# Hugging Face dataset where artifact batches are stored
hf_dataset_id: "zanimal/anti-echo-artifacts"

# Local persistent Chroma collections
chroma_collections:
  topic: "news_topic"
  stance: "news_stance"

# === Embedding models ===
embeddings:
  topic_model: "intfloat/e5-base-v2"                 # high-performing topic model
  stance_model: "Snowflake/snowflake-arctic-embed-l" # ideology-aware stance model
  dim: 1024                                          # stance model dimensionality
  dtype: "float16"                                   # storage-efficient dtype
  pooling: "mean"
  chunk_tokens: 512
  normalize: true

# === Topic inference ===
topics:
  source: "https://raw.githubusercontent.com/AHMerrill/anti-echo-chamber/main/config/topics.json"
  max_topics_per_article: 5
  similarity_threshold: 0.4

# === Summarizer (for stance embeddings) ===
summarizer:
  model: "sshleifer/distilbart-cnn-12-6"             # distilled BART (fast, stable on A100 + CUDA 12.x)
  target_sentences: 5                                # generate 3–5 sentences
  truncation: 3072                                   # broad sampling window
  rhetorical_prompt: true                            # enable persuasion/ideology prompt mode

# === Batch output + artifact management ===
batch:
  base_dir: "batches"
  manifest_name: "manifest.json"
  topic_file: "embeddings_topic.npz"
  stance_file: "embeddings_stance.npz"
  metadata_file: "metadata.jsonl"
  compress: true
  dtype: "float16"
  hf_push: true                                      # automatically push to HF dataset

# === Identifier + hashing scheme ===
ids:
  scheme: "domain-slug-sha12"
  hash: "sha256"
  normalize_whitespace: true
  lowercase: true
  include_timestamp: true

# === Chroma persistence and similarity metric ===
chroma:
  dir: "chroma_db"
  distance_metric: "cosine"
  rebuild_if_missing: true

# === Logging, diagnostics, and recovery ===
logging:
  level: "INFO"
  save_dir: "logs"
  record_failures: true
  checkpoint_interval: 100

# === Diagnostics ===
diagnostics:
  validate_embeddings: true
  sample_summary_preview: true
  max_preview_chars: 500
